{
 "title": "Spring Boot App Detail",
 "time": { "from": "2023-05-20T17:00:00.000Z", "to": "2023-05-20T18:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "influxdb", "query": "influxdb" },
   {
    "name": "app",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"app\",\n  tag: \"appName\",\n  predicate: (r) => r[\"appName\"] =~ /.*-sb/\n)"
   },
   {
    "name": "env",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"app\",\n  tag: \"appEnv\",\n  predicate: (r) => r[\"appName\"] =~ /${app:regex}/\n)"
   },
   {
    "name": "host",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"app\",\n  tag: \"appHost\",\n  predicate: (r) => r[\"appName\"] =~ /${app:regex}/ and r[\"appEnv\"] =~ /${env:regex}/\n)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU%",
   "type": "timeseries",
   "description": "The \"recent cpu usage\" for the Java Virtual Machine process",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_cpu_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")"
    }
   ]
  },
  {
   "title": "Heap Memory%",
   "type": "timeseries",
   "description": "The percentage of used heap memory",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_max\" or r[\"_measurement\"] == \"jvm_memory_used\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"area\"] == \"heap\")\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> map(fn: (r) => ({r with _value: if r._value < 0 then 0.0 else r._value}))\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r.jvm_memory_used / r.jvm_memory_max}))\n  |> map(fn: (r) => ({ r with _measurement: \"jvm_heap_memory_pct\"}))\n  |> drop(columns: [\"jvm_memory_used\",\"jvm_memory_max\"])\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])"
    }
   ]
  },
  {
   "title": "GC Pause",
   "type": "timeseries",
   "description": "Time spent in GC pause",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_gc_pause\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sum\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"histogram\")\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "The current number of live threads including both daemon and non-daemon threads",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_threads_live\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")\n  |> toInt()"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Rate of HTTP server request handling",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_server_requests\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"histogram\")\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "description": "Duration of HTTP server request handling",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_server_requests\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sum\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"histogram\")\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
    }
   ]
  },
  {
   "title": "JVM Heap Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory Max",
     "type": "stat",
     "description": "The maximum amount of memory in bytes that can be used for memory management",
     "gridPos": { "h": 16, "w": 4, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_max\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"area\"] == \"heap\")\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> map(fn: (r) => ({r with _value: if r._value < 0 then 0.0 else r._value}))\n  |> last()\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])\n  |> sum()"
      },
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_max\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"area\"] == \"heap\")\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> map(fn: (r) => ({r with _value: if r._value < 0 then 0.0 else r._value}))\n  |> last()\n"
      }
     ]
    },
    {
     "title": "Heap Memory Used",
     "type": "timeseries",
     "description": "The amount of used memory",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_used\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"area\"] == \"heap\")\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> map(fn: (r) => ({r with _value: if r._value < 0 then 0.0 else r._value}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")"
      },
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_used\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"area\"] == \"heap\")\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    },
    {
     "title": "Heap Memory Committed",
     "type": "timeseries",
     "description": "The amount of memory in bytes that is committed for the Java virtual machine to use",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_committed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"area\"] == \"heap\")\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")"
      },
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_committed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"area\"] == \"heap\")\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Heap Pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory Usage after GC",
     "type": "timeseries",
     "description": "The percentage of long-lived heap pool used after the last GC event",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_usage_after_gc\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"area\"] == \"heap\")\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    },
    {
     "title": "GC Overhead",
     "type": "timeseries",
     "description": "An approximation of the percent of CPU time used by GC activities over the last lookback period or since monitoring began, whichever is shorter",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_gc_overhead\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Non-Heap Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Non-Heap Memory Max",
     "type": "stat",
     "description": "The maximum amount of memory in bytes that can be used for memory management",
     "gridPos": { "h": 16, "w": 4, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_max\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"area\"] == \"nonheap\")\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> map(fn: (r) => ({r with _value: if r._value < 0 then 0.0 else r._value}))\n  |> last()\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])\n  |> sum()"
      },
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_max\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"area\"] == \"nonheap\")\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> map(fn: (r) => ({r with _value: if r._value < 0 then 0.0 else r._value}))\n  |> last()\n"
      }
     ]
    },
    {
     "title": "Non-Heap Memory Used",
     "type": "timeseries",
     "description": "The amount of used memory",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_used\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"area\"] == \"nonheap\")\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> map(fn: (r) => ({r with _value: if r._value < 0 then 0.0 else r._value}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")"
      },
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_used\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"area\"] == \"nonheap\")\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    },
    {
     "title": "Non-Heap Memory Committed",
     "type": "timeseries",
     "description": "The amount of memory in bytes that is committed for the Java virtual machine to use",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_committed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"area\"] == \"nonheap\")\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")"
      },
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_committed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"area\"] == \"nonheap\")\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Pause Duration",
     "type": "timeseries",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_gc_pause\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sum\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"histogram\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
      },
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_gc_pause\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sum\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"histogram\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    },
    {
     "title": "GC Pause Count",
     "type": "timeseries",
     "description": "Amount of GC pause",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_gc_pause\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"histogram\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
      },
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_gc_pause\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"histogram\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    },
    {
     "title": "GC Mem Allocated / Promoted",
     "type": "timeseries",
     "description": "Allocated - Incremented for an increase in the size of the (young) heap memory pool after one GC to before the next <br>\nPromoted - Count of positive increases in the size of the old generation memory pool before GC to after GC",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_gc_memory_allocated\" or r[\"_measurement\"] == \"jvm_gc_memory_promoted\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"counter\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    },
    {
     "title": "GC Data Size",
     "type": "timeseries",
     "description": "Live - Size of long-lived heap memory pool after reclamation <br>\nMax - Max size of long-lived heap memory pool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_gc_live_data_size\" or r[\"_measurement\"] == \"jvm_gc_max_data_size\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread States",
     "type": "timeseries",
     "description": "The current number of threads by state",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_threads_states\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")\n  |> toInt()"
      }
     ]
    },
    {
     "title": "Daemon Threads",
     "type": "timeseries",
     "description": "The current number of live daemon threads",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_threads_daemon\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")\n  |> toInt()"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate",
     "type": "timeseries",
     "description": "Rate of HTTP server request handling",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_server_requests\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"histogram\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "timeseries",
     "description": "Duration of HTTP server request handling",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_server_requests\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sum\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"histogram\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    },
    {
     "title": "Error Request Rate",
     "type": "timeseries",
     "description": "Rate of HTTP server request handling",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_server_requests\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"status\"] >= \"400\")\n  |> filter(fn: (r) => r[\"metric_type\"] == \"histogram\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    },
    {
     "title": "Error Request Duration",
     "type": "timeseries",
     "description": "Duration of HTTP server request handling",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_server_requests\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sum\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"status\"] >= \"400\")\n  |> filter(fn: (r) => r[\"metric_type\"] == \"histogram\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Buffer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Buffer Total Capacity",
     "type": "stat",
     "description": "An estimate of the total capacity of the buffers in this pool",
     "gridPos": { "h": 16, "w": 4, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_buffer_total_capacity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> last()"
      }
     ]
    },
    {
     "title": "JVM Buffer Count",
     "type": "timeseries",
     "description": "An estimate of the number of buffers in the pool",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_buffer_count\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    },
    {
     "title": "JVM Buffer Memory Usage",
     "type": "timeseries",
     "description": "An estimate of the memory that the Java virtual machine is using for this buffer pool",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_buffer_memory_used\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Executor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pool Core Max",
     "type": "stat",
     "description": "The maximum allowed number of threads in the pool",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"executor_pool_max\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> last()"
      }
     ]
    },
    {
     "title": "Pool Size",
     "type": "timeseries",
     "description": "The current number of threads in the pool",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"executor_pool_size\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    },
    {
     "title": "Pool Core",
     "type": "timeseries",
     "description": "The core number of threads for the pool",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"executor_pool_core\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    },
    {
     "title": "Completed",
     "type": "stat",
     "description": "The approximate total number of tasks that have completed execution",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"executor_completed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"counter\")\n  |> last()"
      }
     ]
    },
    {
     "title": "Active / Queued",
     "type": "timeseries",
     "description": "Active - The approximate number of threads that are actively executing tasks <br>\nQueued - The approximate number of tasks that are queued for execution",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"executor_active\" or r[\"_measurement\"] == \"executor_queued\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    },
    {
     "title": "Queue Remaining",
     "type": "timeseries",
     "description": "The number of additional elements that this queue can ideally accept without blocking",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"executor_queue_remaining\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tomcat_sessions_active_max\" or r[\"_measurement\"] == \"tomcat_sessions_alive_max\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> last()"
      }
     ]
    },
    {
     "title": "Active Current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 4, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tomcat_sessions_active_current\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    },
    {
     "title": "Created / Expired / Rejected",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tomcat_sessions_rejected\" or r[\"_measurement\"] == \"tomcat_sessions_expired\" or r[\"_measurement\"] == \"tomcat_sessions_created\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"counter\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Start Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"event\")\n  |> range(start: -30d, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appStart\")\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"appStartTimestamp\")\n  |> last()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_start\",\"_stop\",\"_time\",\"_field\",\"metric_type\"])"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "The uptime of the Java virtual machine",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_uptime\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> last()"
      }
     ]
    },
    {
     "title": "JVM Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"event\")\n  |> range(start: -30d, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appStart\")\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"javaVersion\")\n  |> last()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_start\",\"_stop\",\"_time\",\"_field\",\"metric_type\"])"
      }
     ]
    },
    {
     "title": "Build Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"event\")\n  |> range(start: -30d, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appStart\")\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"buildVersion\")\n  |> last()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_start\",\"_stop\",\"_time\",\"_field\",\"metric_type\"])"
      }
     ]
    },
    {
     "title": "Ready Time",
     "type": "stat",
     "description": "Time taken (ms) for the application to be ready to service requests",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"event\")\n  |> range(start: -30d, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appStart\")\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"appReadyTime\")\n  |> last()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_start\",\"_stop\",\"_time\",\"_field\",\"metric_type\"])"
      }
     ]
    },
    {
     "title": "Max Memory",
     "type": "stat",
     "description": "The maximum amount of memory in bytes that can be used for memory management",
     "gridPos": { "h": 4, "w": 2, "x": 18, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"app\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_max\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> map(fn: (r) => ({r with _value: if r._value < 0 then 0.0 else r._value}))\n  |> last()\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])\n  |> sum(column: \"_value\")"
      }
     ]
    },
    {
     "title": "JVM Classes Loaded",
     "type": "timeseries",
     "description": "The number of classes that are currently loaded in the Java virtual machine",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_classes_loaded\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    },
    {
     "title": "JVM Classes Unloaded",
     "type": "timeseries",
     "description": "The total number of classes unloaded since the Java virtual machine has started execution",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_classes_unloaded\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"counter\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    },
    {
     "title": "Process Files",
     "type": "timeseries",
     "description": "The open file descriptor count",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_files_max\" or r[\"_measurement\"] == \"process_files_open\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")\n  |> toInt()"
      }
     ]
    },
    {
     "title": "JVM Compilation Time",
     "type": "timeseries",
     "description": "The approximate accumulated elapsed time spent in compilation",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_compilation_time\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"counter\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    },
    {
     "title": "Logback Events",
     "type": "timeseries",
     "description": "Number of events that made it to the logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"logback_events\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"counter\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
      }
     ]
    }
   ]
  }
 ]
}