{
 "title": "Spring Boot App Overview",
 "time": { "from": "2023-05-20T17:00:00.000Z", "to": "2023-05-20T18:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "influxdb", "query": "influxdb" },
   {
    "name": "app",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"app\",\n  tag: \"appName\",\n  predicate: (r) => r[\"appName\"] =~ /.*-sb/\n)"
   },
   {
    "name": "env",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"app\",\n  tag: \"appEnv\",\n  predicate: (r) => r[\"appName\"] =~ /${app:regex}/\n)"
   },
   {
    "name": "host",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"app\",\n  tag: \"appHost\",\n  predicate: (r) => r[\"appName\"] =~ /${app:regex}/ and r[\"appEnv\"] =~ /${env:regex}/\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_cpu_usage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")"
    }
   ]
  },
  {
   "title": "Heap Memory%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_memory_max\" or r[\"_measurement\"] == \"jvm_memory_used\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"area\"] == \"heap\")\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> map(fn: (r) => ({r with _value: if r._value < 0 then 0.0 else r._value}))\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: r.jvm_memory_used / r.jvm_memory_max}))\n  |> map(fn: (r) => ({ r with _measurement: \"jvm_heap_memory_pct\"}))\n  |> drop(columns: [\"jvm_memory_used\",\"jvm_memory_max\"])\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])"
    }
   ]
  },
  {
   "title": "GC Pause",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_gc_pause\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sum\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"histogram\")\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jvm_threads_live\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false, timeSrc: \"_start\")\n  |> toInt()"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_server_requests\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"histogram\")\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"app\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit:v.windowPeriod), stop: date.truncate(t: v.timeRangeStop, unit:v.windowPeriod))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_server_requests\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sum\")\n  |> filter(fn: (r) => r[\"appEnv\"] =~ /${env:regex}/)\n  |> filter(fn: (r) => r[\"appHost\"] =~ /${host:regex}/)\n  |> filter(fn: (r) => r[\"appName\"] =~ /${app:regex}/)\n  |> filter(fn: (r) => r[\"metric_type\"] == \"histogram\")\n  |> group(columns: [\"appName\",\"appEnv\",\"appHost\",\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false, timeSrc: \"_start\")"
    }
   ]
  }
 ]
}